# Generated by Django 3.0.3 on 2020-02-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view', 'user has read permission'), ('create', 'user has write permissions'), ('edit', 'user has edit permissions')]},
        ),
    ]
