# Generated by Django 3.0.3 on 2020-02-15 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view', 'user has read permission'), ('create', 'user has write permissions'), ('edit', 'user has edit permissions')], 'verbose_name': 'Regular User', 'verbose_name_plural': 'Regular Users'},
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(help_text='Select the users you manage', related_name='user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administartors',
            },
            bases=('users.customuser',),
        ),
    ]
