# Generated by Django 3.0.3 on 2020-02-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200215_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view', 'user has read permission'), ('create', 'user has write permissions'), ('edit', 'user has edit permissions')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
